GET   http://127.0.0.1:5000/users/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNjc4ODMxMywianRpIjoiZWM4ZmQ2MWMtNWIwYy00YmE4LWI0OTItZWQ3YzRkY2Y3YjNkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6Mywicm9sZSI6ImFkbWluIn0sIm5iZiI6MTcyNjc4ODMxMywiY3NyZiI6IjYzZmZjMGExLTNiMDctNDc2Yy04ODJiLWUxMzI4MTc3YjQzNyIsImV4cCI6MTcyNjc4OTIxM30.0mcwtuGvidb24iEcL2m00NBKHj6tlgZfahW4DnALe3s


### register
POST http://127.0.0.1:5000/users/register
Content-Type: application/json

    {
        "name":"elias",
        "password":"elias",
        "email":"elias@gmail.com",
        "contact":"0768543269",
        "address":"nairobi",
        "username":"chege"
    }


###login
POST http://127.0.0.1:5000/users/login
Content-Type: application/json

    {
        "email":"elias@gmail.com",
        "password":"elias"
    }

###update user
PUT http://127.0.0.1:5000/users/3
Content-Type: application/json

{   
    "role": "ADMIN"
}

### delete user
DELETE http://127.0.0.1:5000/users/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNjY5NTQ2NCwianRpIjoiOWFiZWIwNzAtNDZiYS00NDhmLTk3NzYtNGQ0OGM1OTg5ZjQzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6Mywicm9sZSI6ImFkbWluIn0sIm5iZiI6MTcyNjY5NTQ2NCwiY3NyZiI6ImU0ZWEwZmY2LTFiNTItNDRkNy05NGZlLTdkY2JlYjAxZjE4ZSIsImV4cCI6MTcyNjY5NjM2NH0.2swE54GdC1QgWee5std33Eoe4Nh98ZeYpGt4P3dPYsI